### ISSUE TITLE
Instance Mithril Mines

### ISSUE THREAD

**Issue by valanths1990** [L2JGeo/L2J_Geodata_Hi5#4]
Mithril mines have some issues with geodata
player can climb:

http://prntscr.com/98tqk8

**Comment by maneco2** [comment]
which the coordinates?

**Comment by valanths1990** [comment]
yes sorry:

x:185427 y: -182507 z: -3168

Geo file: 25_12

**Comment by maneco2** [comment]
there is no problem here, it was always possible to climb up only at the end
https://cdn.pbrd.co/images/2zojrtBY.jpg

**Comment by valanths1990** [comment]
there was a strange movement when i click down
 thats why i report it
all tests made using latest l2j release(develop)

you can close it
